[workspace]
authors = ["Marvin Albert <marvin.albert@gmail.com>"]
channels = ["conda-forge"]
name = "CQ3000_converter"
platforms = ["osx-arm64", "win-64", "linux-64"]
version = "0.1.0"

[tasks]
# CQ3000 Converter CLI - Entry point to the Typer CLI
convert-to-ome-zarr = "python convert_to_ome_zarr.py"